-- Run this script in your Supabase SQL Editor to set up the database

-- 1. Create the orders table (Used by the Dashboard & AppContext)
CREATE TABLE IF NOT EXISTS public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id text,
    customer_name text,
    items jsonb, -- Stores the cart items as a JSON array
    subtotal numeric,
    tax numeric,
    discount numeric DEFAULT 0,
    total numeric,
    amount_paid numeric,
    status text,
    payment_method text,
    created_at timestamptz DEFAULT now()
);

-- 2. Create the order_forms table (Used by the Checkout Form)
CREATE TABLE IF NOT EXISTS public.order_forms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name text NOT NULL,
    last_name text,
    street text,
    locality text,
    pin_code text,
    mobile_no text NOT NULL,
    product_name text NOT NULL,
    quantity integer DEFAULT 1,
    total_amount numeric DEFAULT 0,
    created_at timestamptz DEFAULT now()
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_forms ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies to allow access (Public Read/Write for Demo)

-- Policies for 'orders'
DROP POLICY IF EXISTS "Enable read access for all users" ON public.orders;
CREATE POLICY "Enable read access for all users" ON public.orders
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert access for all users" ON public.orders;
CREATE POLICY "Enable insert access for all users" ON public.orders
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Enable update access for all users" ON public.orders;
CREATE POLICY "Enable update access for all users" ON public.orders
    FOR UPDATE USING (true);

-- Policies for 'order_forms'
DROP POLICY IF EXISTS "Enable read access for all users" ON public.order_forms;
CREATE POLICY "Enable read access for all users" ON public.order_forms
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert access for all users" ON public.order_forms;
CREATE POLICY "Enable insert access for all users" ON public.order_forms
    FOR INSERT WITH CHECK (true);
